const reason = { width: 400, height: 300 };

export const graphics = [
  {
    name: "reason-sources",
    template: "reason-sources.html",
    ...reason,
    dark: "docs/images/reason-sources-dark.png",
    light: "docs/images/reason-sources-light.png",
    shows: "Available",
    label: null,
    alt: "Cited answers only from the documents of the business",
  },
  {
    name: "reason-citations",
    template: "reason-citations.html",
    ...reason,
    dark: "docs/images/reason-citations-dark.png",
    light: "docs/images/reason-citations-light.png",
    shows: "Available",
    label: null,
    alt: "Every passage of Cited carries its document, its heading and its position",
  },
  {
    name: "reason-voice",
    template: "reason-voice.html",
    ...reason,
    dark: "docs/images/reason-voice-dark.png",
    light: "docs/images/reason-voice-light.png",
    shows: "Planned",
    label: "Next",
    alt: "Voice with ElevenLabs, planned for the next change",
  },
  {
    name: "how-it-works",
    template: "how-it-works.html",
    width: 1280,
    height: 480,
    dark: "docs/images/how-it-works-dark.png",
    light: "docs/images/how-it-works-light.png",
    shows: "Planned",
    label: "Next",
    alt: "How Cited works: documents, passages, libSQL, Reciprocal Rank Fusion and the answer",
  },
  {
    name: "demo",
    template: "demo.html",
    width: 1280,
    height: 560,
    dark: "docs/images/demo-dark.png",
    light: "docs/images/demo-light.png",
    shows: "Available",
    label: null,
    alt: "A real run of the quick start of Cited: ingestion and one search",
  },
  {
    name: "roadmap",
    template: "roadmap.html",
    width: 1280,
    height: 440,
    dark: "docs/images/roadmap-dark.png",
    light: "docs/images/roadmap-light.png",
    shows: "Planned",
    label: "Next",
    alt: "The roadmap of Cited: what is available today and what each next change adds",
  },
  {
    name: "voice-teaser",
    template: "voice-teaser.html",
    width: 1280,
    height: 360,
    dark: "docs/images/voice-teaser-dark.png",
    light: "docs/images/voice-teaser-light.png",
    shows: "Planned",
    label: "Next",
    alt: "Voice agent of Cited, planned for the ElevenLabs change",
  },
];

export const social = {
  name: "social-preview",
  template: "social.html",
  width: 1280,
  height: 640,
  dark: "docs/images/social-preview.png",
  alt: "Cited, by Katalis: answers from your own documents",
};

export const logo = {
  name: "katalis-logo",
  template: "logo.html",
  light: "docs/images/katalis-logo.png",
  dark: "docs/images/katalis-logo-dark.png",
  alt: "Katalis",
};
