const reason = { width: 400, height: 300 };

export const graphics = [
  {
    name: "reason-sources",
    template: "reason-sources.html",
    ...reason,
    dark: "docs/images/reason-sources-dark.png",
    light: "docs/images/reason-sources-light.png",
    headline: "Only your documents.",
    copy: "No web, no memory, no guess.",
    shows: "Available",
    label: null,
    alt: "Cited reads only the documents you point it at",
  },
  {
    name: "reason-citations",
    template: "reason-citations.html",
    ...reason,
    dark: "docs/images/reason-citations-dark.png",
    light: "docs/images/reason-citations-light.png",
    headline: "Every passage keeps its source.",
    copy: "Document, heading and position.",
    shows: "Available",
    label: null,
    alt: "Every passage of Cited carries its document, its heading and its position",
  },
  {
    name: "reason-voice",
    template: "reason-voice.html",
    ...reason,
    dark: "docs/images/reason-voice-dark.png",
    light: "docs/images/reason-voice-light.png",
    headline: "Talk to it.",
    copy: "Voice with ElevenLabs is next.",
    shows: "Planned",
    label: "Next",
    alt: "Voice with ElevenLabs, planned for the next change",
  },
  {
    name: "how-it-works",
    template: "how-it-works.html",
    width: 1280,
    height: 480,
    dark: "docs/images/how-it-works-dark.png",
    light: "docs/images/how-it-works-light.png",
    headline: "From a folder of documents to a cited passage",
    copy: null,
    shows: "Available",
    label: null,
    alt: "How Cited works: documents, passages, libSQL, Reciprocal Rank Fusion and the answer with its numbered citations, with the voice marked Next",
  },
  {
    name: "demo",
    template: "demo.html",
    width: 1280,
    height: 720,
    dark: "docs/images/demo-dark.png",
    light: "docs/images/demo-light.png",
    headline: "Ask a question. Get the passage and where it came from.",
    copy: null,
    shows: "Available",
    label: null,
    alt: "A real run of the quick start of Cited: ingestion, one search and one answer with its citation",
  },
  {
    name: "roadmap",
    template: "roadmap.html",
    width: 1280,
    height: 700,
    dark: "docs/images/roadmap-dark.png",
    light: "docs/images/roadmap-light.png",
    headline: "What runs today, and what comes next",
    copy: null,
    shows: "Planned",
    label: "Next",
    alt: "The roadmap of Cited: what is available today and what each next change adds",
  },
  {
    name: "voice-teaser",
    template: "voice-teaser.html",
    width: 1280,
    height: 360,
    dark: "docs/images/voice-teaser-dark.png",
    light: "docs/images/voice-teaser-light.png",
    headline: "Talk to your documents.",
    copy: null,
    shows: "Planned",
    label: "Next",
    alt: "Voice agent of Cited, planned for the ElevenLabs change",
  },
];

export const social = {
  name: "social-preview",
  template: "social.html",
  width: 1280,
  height: 640,
  dark: "docs/images/social-preview.png",
  alt: "Cited, by Katalis: ask your own documents and get the passage and where it came from",
};
