// @vitest-environment node
import { randomBytes } from "node:crypto";
import { afterAll, describe, expect, it } from "vitest";
import { DELETE as providersDelete, GET as providersGet } from "@/app/api/admin/providers/route";
import { POST as providersReindex } from "@/app/api/admin/providers/reindex/route";
import { POST as providersSave } from "@/app/api/admin/providers/save/route";
import { POST as providersTest } from "@/app/api/admin/providers/test/route";
import { sessionToken } from "@/lib/admin/session";
import { TEST_TIMEOUT_MS } from "@/lib/providers/test";
import { sharedStore } from "@/lib/store/instance";
import {
  ADMIN_SECRET,
  adminRequest,
  cleanup,
  configured,
  environmentOf,
  sessionHeader,
} from "./admin-helpers";
import {
  anthropicAnswer,
  geminiAnswer,
  openAiChatAnswer,
  openAiEmbeddingsAnswer,
  providerDouble,
  type ProviderDouble,
} from "./provider-double";

// Every scenario of `specs/provider-settings/spec.md`, with a local HTTP double for every provider and never a call to
// a real one. The keys of this file are generated by the run.

const encryptionKey = randomBytes(32).toString("base64");
const doubleKey = "sk-del-doble-0000000000007788";
const doubles: ProviderDouble[] = [];

afterAll(async () => {
  for (const double of doubles) {
    await double.close();
  }

  await cleanup();
});

async function double(
  handler: Parameters<typeof providerDouble>[0],
): Promise<ProviderDouble> {
  const started = await providerDouble(handler);

  doubles.push(started);

  return started;
}

function token(): string {
  return sessionToken(ADMIN_SECRET, new Date());
}

function test(body: unknown, headers: Record<string, string> = {}): Promise<Response> {
  return providersTest(
    adminRequest("http://localhost/api/admin/providers/test", {
      method: "POST",
      headers: { ...sessionHeader(token()), ...headers },
      body: JSON.stringify(body),
    }),
  );
}

// The doubles of this file listen on `127.0.0.1` and the routes send their URL as the `baseUrl` of the body, so the
// environment of the case has to say the three things an installation with a provider of its own says: the address of
// the provider is the one of the server (never a value of the browser), and the local address is allowed because this
// installation runs its provider on its own machine (requirement "A provider address cannot reach private networks").
function withDouble(
  baseUrl: string,
  overrides: Record<string, string | undefined>,
  provider = "openai",
): Record<string, string | undefined> {
  const variable: Record<string, string> = {
    openai: "OPENAI_BASE_URL",
    anthropic: "ANTHROPIC_BASE_URL",
    gemini: "GEMINI_BASE_URL",
    ollama: "OLLAMA_BASE_URL",
  };
  const name = variable[provider] ?? "OPENAI_BASE_URL";

  return { ...overrides, [name]: baseUrl, ALLOW_LOCAL_PROVIDERS: "1" };
}

function save(body: unknown, headers: Record<string, string> = {}): Promise<Response> {
  return providersSave(
    adminRequest("http://localhost/api/admin/providers/save", {
      method: "POST",
      headers: { ...sessionHeader(token()), ...headers },
      body: JSON.stringify(body),
    }),
  );
}

function state(headers: Record<string, string> = {}): Promise<Response> {
  return providersGet(
    adminRequest("http://localhost/api/admin/providers", {
      headers: { ...sessionHeader(token()), ...headers },
    }),
  );
}

type TestBody = {
  status: string;
  ok?: boolean;
  reason?: string;
  model?: string;
  latencyMs?: number;
  saved?: boolean;
  last4?: string;
  error?: string;
};

type ViewBody = {
  source: string;
  provider: string | null;
  model: string;
  last4: string | null;
  mode: string | null;
};

describe("POST /api/admin/providers/test", () => {
  it("answers 401 without the session and never calls the provider", async () => {
    const seen = await double(() => ({ status: 200, body: openAiChatAnswer() }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));
    const response = await providersTest(
      adminRequest("http://localhost/api/admin/providers/test", {
        method: "POST",
        body: JSON.stringify({
          kind: "chat",
          provider: "openai",
          key: doubleKey,
          baseUrl: `${seen.url}/v1`,
        }),
      }),
    );

    expect(response.status).toBe(401);
    expect(seen.requests).toEqual([]);
  });

  it("tests a good key of an OpenAI-compatible provider and answers its model and latency", async () => {
    const seen = await double(() => ({ status: 200, body: openAiChatAnswer() }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));
    const response = await test({
      kind: "chat",
      provider: "openai",
      key: doubleKey,
      model: "gpt-4o-mini",
      baseUrl: `${seen.url}/v1`,
    });
    const body = (await response.json()) as TestBody;

    expect(response.status).toBe(200);
    expect(body.ok).toBe(true);
    expect(body.model).toBe("gpt-4o-mini");
    expect(typeof body.latencyMs).toBe("number");
    expect(body.latencyMs).toBeGreaterThanOrEqual(0);
    expect(seen.requests).toHaveLength(1);
    expect(seen.requests[0]?.method).toBe("POST");
    expect(seen.requests[0]?.path).toBe("/v1/chat/completions");
    expect(seen.requests[0]?.authorization).toBe(`Bearer ${doubleKey}`);
    expect(seen.requests[0]?.body?.["model"]).toBe("gpt-4o-mini");
  });

  it("says the provider rejected the key and carries no text of the provider error", async () => {
    const seen = await double(() => ({
      status: 401,
      body: { error: { message: `Incorrect API key provided: ${doubleKey}`, code: "invalid_api_key" } },
    }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));
    const response = await test({
      kind: "chat",
      provider: "openai",
      key: doubleKey,
      baseUrl: `${seen.url}/v1`,
    });
    const text = await response.text();

    expect(response.status).toBe(200);
    expect(JSON.parse(text)).toEqual({ status: "ok", ok: false, reason: "rejected_key" });
    expect(text).not.toContain("Incorrect API key");
    expect(text).not.toContain(doubleKey);
  });

  it("reads no credit, a missing model and a rate limit apart", async () => {
    const noCredit = await double(() => ({ status: 402, body: { error: { message: "no credit" } } }));
    const quota = await double(() => ({
      status: 429,
      body: { error: { message: "You exceeded your current quota", code: "insufficient_quota" } },
    }));
    const limited = await double(() => ({
      status: 429,
      body: { error: { message: "Rate limit reached", code: "rate_limit_exceeded" } },
    }));
    const missing = await double(() => ({
      status: 404,
      body: { error: { message: "The model does not exist", code: "model_not_found" } },
    }));
    // Gemini answers 400 with `API_KEY_INVALID` for a key it refuses, not 401: it is still a rejected key.
    const gemini = await double(() => ({
      status: 400,
      body: { error: { message: "API key not valid. Please pass a valid API key.", status: "INVALID_ARGUMENT" } },
    }));

    // The address of each provider is the one the server has: `withDouble()` writes it, and the routes send the same
    // value in the body, which is what a panel does with the address of its own catalogue.
    await environmentOf({
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
      ALLOW_LOCAL_PROVIDERS: "1",
      OPENAI_BASE_URL: `${noCredit.url}/v1`,
      GEMINI_BASE_URL: `${gemini.url}/v1beta`,
    });

    expect(
      (await (
        await test({ kind: "chat", provider: "openai", key: doubleKey, baseUrl: `${noCredit.url}/v1` })
      ).json()) as TestBody,
    ).toEqual({ status: "ok", ok: false, reason: "no_credit" });

    expect(
      (await (
        await test({ kind: "chat", provider: "openai", key: doubleKey, baseUrl: `${quota.url}/v1` })
      ).json()) as TestBody,
    ).toEqual({ status: "ok", ok: false, reason: "no_credit" });

    expect(
      (await (
        await test({ kind: "chat", provider: "openai", key: doubleKey, baseUrl: `${limited.url}/v1` })
      ).json()) as TestBody,
    ).toEqual({ status: "ok", ok: false, reason: "rate_limited" });

    expect(
      (await (
        await test({ kind: "chat", provider: "openai", key: doubleKey, baseUrl: `${missing.url}/v1` })
      ).json()) as TestBody,
    ).toEqual({ status: "ok", ok: false, reason: "model_not_found" });

    expect(
      (await (
        await test({
          kind: "chat",
          provider: "gemini",
          key: doubleKey,
          baseUrl: `${gemini.url}/v1beta`,
        })
      ).json()) as TestBody,
    ).toEqual({ status: "ok", ok: false, reason: "rejected_key" });
  });

  it("calls Anthropic, Gemini and Ollama with the shape each one expects", async () => {
    const anthropic = await double(() => ({ status: 200, body: anthropicAnswer() }));
    const gemini = await double(() => ({ status: 200, body: geminiAnswer() }));
    const ollama = await double(() => ({ status: 200, body: openAiChatAnswer() }));

    await environmentOf({
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
      ALLOW_LOCAL_PROVIDERS: "1",
      ANTHROPIC_BASE_URL: `${anthropic.url}/v1`,
      GEMINI_BASE_URL: `${gemini.url}/v1beta`,
      OLLAMA_BASE_URL: `${ollama.url}/v1`,
    });

    expect(
      (await (
        await test({
          kind: "chat",
          provider: "anthropic",
          key: doubleKey,
          model: "claude-haiku-4-5-20251001",
          baseUrl: `${anthropic.url}/v1`,
        })
      ).json()) as TestBody,
    ).toMatchObject({ ok: true, model: "claude-haiku-4-5-20251001" });
    expect(anthropic.requests[0]?.path).toBe("/v1/messages");
    expect(anthropic.requests[0]?.headers["x-api-key"]).toBe(doubleKey);

    expect(
      (await (
        await test({
          kind: "chat",
          provider: "gemini",
          key: doubleKey,
          model: "gemini-3.8-flash",
          baseUrl: `${gemini.url}/v1beta`,
        })
      ).json()) as TestBody,
    ).toMatchObject({ ok: true, model: "gemini-3.8-flash" });
    expect(gemini.requests[0]?.path).toContain("/v1beta/models/gemini-3.8-flash:generateContent");
    expect(gemini.requests[0]?.path).toContain(`key=${doubleKey}`);

    expect(
      (await (
        await test({
          kind: "chat",
          provider: "ollama",
          key: "",
          model: "llama3.1",
          baseUrl: `${ollama.url}/v1`,
        })
      ).json()) as TestBody,
    ).toMatchObject({ ok: true, model: "llama3.1" });
    expect(ollama.requests[0]?.path).toBe("/v1/chat/completions");
    expect(ollama.requests[0]?.authorization).toBeNull();
  });

  it("tests an embeddings provider with one short text", async () => {
    const seen = await double(() => ({ status: 200, body: openAiEmbeddingsAnswer(1536) }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));
    const response = await test({
      kind: "embeddings",
      provider: "openai",
      key: doubleKey,
      model: "text-embedding-3-small",
      baseUrl: `${seen.url}/v1`,
    });

    expect(response.status).toBe(200);
    expect(((await response.json()) as TestBody).ok).toBe(true);
    expect(seen.requests[0]?.path).toBe("/v1/embeddings");
    expect(seen.requests[0]?.authorization).toBe(`Bearer ${doubleKey}`);
    expect(seen.requests[0]?.body?.["model"]).toBe("text-embedding-3-small");
  });

  it("times out on a provider that never answers, and its default is ten seconds", async () => {
    const seen = await double(() => ({ status: 200, hang: true }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
      PROVIDER_TEST_TIMEOUT_MS: "200",
    }));
    const started = Date.now();
    const response = await test({
      kind: "chat",
      provider: "openai",
      key: doubleKey,
      baseUrl: `${seen.url}/v1`,
    });

    expect(TEST_TIMEOUT_MS).toBe(10_000);
    expect(((await response.json()) as TestBody).reason).toBe("timeout");
    expect(Date.now() - started).toBeLessThan(5_000);
  });

  it("answers unreachable when nothing listens on the address", async () => {
    const closed = await double(() => ({ status: 200, body: {} }));
    await environmentOf(withDouble(closed.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));
    const url = closed.url;

    await closed.close();

    const response = await test({
      kind: "chat",
      provider: "openai",
      key: doubleKey,
      baseUrl: `${url}/v1`,
    });

    expect(((await response.json()) as TestBody).reason).toBe("unreachable");
  });

  it("answers 429 after twenty tests in an hour and keeps the panel from spending more", async () => {
    const seen = await double(() => ({ status: 200, body: openAiChatAnswer() }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));

    for (let attempt = 1; attempt <= 20; attempt += 1) {
      const response = await test({
        kind: "chat",
        provider: "openai",
        key: doubleKey,
        baseUrl: `${seen.url}/v1`,
      });

      expect(response.status, `attempt ${attempt}`).toBe(200);
    }

    const limited = await test({
      kind: "chat",
      provider: "openai",
      key: doubleKey,
      baseUrl: `${seen.url}/v1`,
    });

    expect(limited.status).toBe(429);
    expect(((await limited.json()) as TestBody).reason).toBe("rate_limited");
    expect(Number(limited.headers.get("retry-after"))).toBeGreaterThanOrEqual(1);
    expect(seen.requests).toHaveLength(20);
  });

  it("refuses a body that does not name a kind and a provider", async () => {
    const seen = await double(() => ({ status: 200, body: openAiChatAnswer() }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));
    const response = await test({ provider: "openai", key: doubleKey });

    expect(response.status).toBe(400);
    expect(seen.requests).toEqual([]);
  });
});

describe("POST /api/admin/providers/save", () => {
  it("tests first, saves the key encrypted and answers only the last four characters", async () => {
    const seen = await double(() => ({ status: 200, body: openAiChatAnswer() }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));
    const response = await save({
      kind: "chat",
      provider: "openai",
      key: doubleKey,
      model: "gpt-4o-mini",
      baseUrl: `${seen.url}/v1`,
    });
    const body = (await response.json()) as TestBody;

    expect(response.status).toBe(200);
    expect(body.saved).toBe(true);
    expect(body.last4).toBe("7788");
    expect(JSON.stringify(body)).not.toContain(doubleKey);
    expect(seen.requests).toHaveLength(1);

    const store = await sharedStore(process.env);
    const row = await store.readProviderSetting("chat");

    expect(row?.provider).toBe("openai");
    expect(row?.model).toBe("gpt-4o-mini");
    expect(row?.keyCiphertext?.startsWith("v1:")).toBe(true);
    expect(JSON.stringify(row)).not.toContain(doubleKey);
    expect(row?.keyLast4).toBe("7788");
    expect(row?.testedAt).not.toBeNull();
    expect(row?.testLatencyMs).toBeGreaterThanOrEqual(0);
  });

  it("saves nothing when the provider rejects the key", async () => {
    const seen = await double(() => ({ status: 401, body: { error: { message: "nope" } } }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));
    const response = await save({
      kind: "chat",
      provider: "openai",
      key: doubleKey,
      baseUrl: `${seen.url}/v1`,
    });

    expect(await response.json()).toEqual({ status: "ok", saved: false, reason: "rejected_key" });
    expect(((await state()).status)).toBe(200);
    expect(((await (await state()).json()) as { chat: ViewBody }).chat.source).toBe("none");
  });

  it("says the server needs an encryption key when it has none, without naming a variable", async () => {
    const seen = await double(() => ({ status: 200, body: openAiChatAnswer() }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: "",
    }));
    const response = await save({
      kind: "chat",
      provider: "openai",
      key: doubleKey,
      baseUrl: `${seen.url}/v1`,
    });
    const body = (await response.json()) as TestBody;

    expect(response.status).toBe(503);
    expect(body.status).toBe("no_encryption_key");
    expect(body.error?.toLowerCase()).toContain("encryption key");
    expect(body.error).not.toContain("ENCRYPTION_KEY");
    expect(body.error).not.toContain(doubleKey);
    expect(seen.requests).toEqual([]);
  });

  it("saves keyword search without calling any provider and without a key", async () => {
    const seen = await double(() => ({ status: 200, body: openAiChatAnswer() }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));
    const response = await save({ kind: "embeddings", mode: "keyword" });
    const body = (await response.json()) as TestBody;

    expect(response.status).toBe(200);
    expect(body.saved).toBe(true);
    expect(seen.requests).toEqual([]);

    const shown = (await (await state()).json()) as { embeddings: ViewBody };

    expect(shown.embeddings.source).toBe("panel");
    expect(shown.embeddings.mode).toBe("keyword");
  });

  it("removes the panel value and answers the state without it", async () => {
    const seen = await double(() => ({ status: 200, body: openAiChatAnswer() }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));

    await save({
      kind: "chat",
      provider: "openai",
      key: doubleKey,
      baseUrl: `${seen.url}/v1`,
    });

    const removed = await providersDelete(
      adminRequest("http://localhost/api/admin/providers", {
        method: "DELETE",
        headers: sessionHeader(token()),
        body: JSON.stringify({ kind: "chat" }),
      }),
    );

    expect(removed.status).toBe(200);
    expect(((await (await state()).json()) as { chat: ViewBody }).chat.source).toBe("none");
  });
});

describe("GET /api/admin/providers", () => {
  it("shows the last four characters and never the key nor its ciphertext", async () => {
    const seen = await double(() => ({ status: 200, body: openAiChatAnswer() }));
    await environmentOf(withDouble(seen.url, {
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
    }));

    await save({
      kind: "chat",
      provider: "openai",
      key: doubleKey,
      model: "gpt-4o-mini",
      baseUrl: `${seen.url}/v1`,
    });

    const response = await state();
    const text = await response.text();
    const body = JSON.parse(text) as {
      chat: ViewBody;
      embeddings: ViewBody;
      encryption: boolean;
      reindex: { documents: number; passages: number };
    };
    const store = await sharedStore(process.env);
    const row = await store.readProviderSetting("chat");

    expect(response.status).toBe(200);
    expect(body.chat.source).toBe("panel");
    expect(body.chat.model).toBe("gpt-4o-mini");
    expect(body.chat.last4).toBe("7788");
    expect(body.encryption).toBe(true);
    expect(text).not.toContain(doubleKey);
    expect(text).not.toContain(String(row?.keyCiphertext));
    expect(text).not.toContain("v1:");
  });

  it("shows the server as the source and never a value of its variables", async () => {
    await environmentOf({
      ...configured(),
      CHAT_PROVIDER: "fake",
      EMBEDDINGS_PROVIDER: "fake",
      OPENAI_API_KEY: "",
    });

    const body = (await (await state()).json()) as {
      chat: { source: string };
      embeddings: { source: string };
      encryption: boolean;
    };

    expect(body.chat.source).toBe("server");
    expect(body.embeddings.source).toBe("server");
    expect(body.encryption).toBe(false);
  });

  it("carries no variable name in the state of the panel", async () => {
    await environmentOf({
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
      // The doubles of this file listen on `127.0.0.1`, and the requirement "A provider address cannot reach private
      // networks" refuses a loopback address unless whoever installs allows it: this is the flag of an installation
      // that runs its provider on its own machine, which is what this suite does.
      ALLOW_LOCAL_PROVIDERS: "1",
    });

    const text = await (await state()).text();

    expect(text).not.toContain("ENCRYPTION_KEY");
    expect(text).not.toContain("OPENAI_API_KEY");
    expect(text).not.toContain("v1:");
  });

  it("keeps the same session and origin gate as the rest of the panel", async () => {
    await environmentOf({
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
      // The doubles of this file listen on `127.0.0.1`, and the requirement "A provider address cannot reach private
      // networks" refuses a loopback address unless whoever installs allows it: this is the flag of an installation
      // that runs its provider on its own machine, which is what this suite does.
      ALLOW_LOCAL_PROVIDERS: "1",
    });

    const withoutSession = await providersGet(
      adminRequest("http://localhost/api/admin/providers", {}),
    );

    expect(withoutSession.status).toBe(401);

    const fromAnotherSite = await test(
      { kind: "chat", provider: "openai", key: doubleKey },
      { origin: "https://otro-sitio.example" },
    );

    expect(fromAnotherSite.status).toBe(403);
  });
});

describe("POST /api/admin/providers/reindex", () => {
  it("re-embeds nothing and answers zero when the store is empty", async () => {
    await environmentOf({
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
      EMBEDDINGS_PROVIDER: "fake",
      ALLOW_LOCAL_PROVIDERS: "1",
    });

    const response = await providersReindex(
      adminRequest("http://localhost/api/admin/providers/reindex", {
        method: "POST",
        headers: sessionHeader(token()),
        body: JSON.stringify({}),
      }),
    );

    expect(response.status).toBe(200);
    expect(await response.json()).toMatchObject({ status: "ok", documents: 0, passages: 0 });
  });

  it("answers 401 without the session", async () => {
    await environmentOf({
      ...configured(),
      ENCRYPTION_KEY: encryptionKey,
      // The doubles of this file listen on `127.0.0.1`, and the requirement "A provider address cannot reach private
      // networks" refuses a loopback address unless whoever installs allows it: this is the flag of an installation
      // that runs its provider on its own machine, which is what this suite does.
      ALLOW_LOCAL_PROVIDERS: "1",
    });

    const response = await providersReindex(
      adminRequest("http://localhost/api/admin/providers/reindex", { method: "POST", body: "{}" }),
    );

    expect(response.status).toBe(401);
  });
});
