// @vitest-environment node
import { randomBytes } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { sealSecret } from "@/lib/secrets";
import {
  chatConfigured,
  chatProblem,
  embeddingsProblem,
  embeddingsSignature,
  resolveChat,
  resolveEmbeddings,
} from "@/lib/settings/providers";
import { openStore, storeTables, type Store } from "@/lib/store";

// Requirement "The server wins over the panel" of `specs/provider-settings/spec.md` and decisions 3 and 5 of
// `design.md`: one resolver reads the provider of the answers and of the ingestion, a value set on the server wins,
// the panel's value comes next and "none" is a state of its own. The key of this file is generated by the run.

const key = randomBytes(32).toString("base64");
const otherKey = randomBytes(32).toString("base64");
const panelKey = "sk-panel-0000000000009876";
const roots: string[] = [];
const opened: Store[] = [];

async function freshStore(): Promise<Store> {
  const root = mkdtempSync(join(tmpdir(), "cited-settings-"));
  const store = await openStore(join(root, "store.sqlite"));

  roots.push(root);
  opened.push(store);

  return store;
}

async function withPanelChat(store: Store, row: Record<string, unknown>): Promise<void> {
  const sealed = sealSecret(String(row["key"] ?? panelKey), { ENCRYPTION_KEY: key });

  if (sealed.ok === false) {
    throw new Error("the seal failed");
  }

  await store.saveProviderSetting({
    kind: "chat",
    provider: String(row["provider"] ?? "deepseek"),
    model: (row["model"] as string | undefined) ?? "deepseek-flash",
    keyCiphertext: sealed.value,
    keyLast4: panelKey.slice(-4),
    baseUrl: (row["baseUrl"] as string | undefined) ?? null,
    mode: null,
    testedAt: "2026-09-29T10:00:00.000Z",
    testLatencyMs: 120,
  });
}

afterAll(async () => {
  for (const store of opened) {
    store.close();
  }

  for (const root of roots) {
    for (let attempt = 0; attempt < 10; attempt += 1) {
      try {
        rmSync(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
        break;
      } catch {
        await new Promise((wake) => setTimeout(wake, 200));
      }
    }
  }
});

describe("resolveChat", () => {
  it("uses the server value first and leaves the panel behind it", async () => {
    const store = await freshStore();

    await withPanelChat(store, { provider: "openai", model: "gpt-4o-mini" });

    const resolution = await resolveChat({
      environment: {
        ENCRYPTION_KEY: key,
        CHAT_PROVIDER: "deepseek",
        CHAT_MODEL: "deepseek-chat",
        DEEPSEEK_API_KEY: "llave-del-servidor",
      },
      store,
    });

    expect(resolution.source).toBe("server");
    expect(resolution.provider).toBe("deepseek");
    expect(resolution.model).toBe("deepseek-chat");
    expect(resolution.key).toBe("llave-del-servidor");
    expect(resolution.missing).toEqual([]);
    expect(chatProblem(resolution)).toBeNull();
  });

  it("takes the panel value when the server sets none, with the key opened in the server process", async () => {
    const store = await freshStore();

    await withPanelChat(store, {});

    const resolution = await resolveChat({ environment: { ENCRYPTION_KEY: key }, store });

    expect(resolution.source).toBe("panel");
    expect(resolution.provider).toBe("deepseek");
    expect(resolution.model).toBe("deepseek-flash");
    expect(resolution.key).toBe(panelKey);
    expect(chatProblem(resolution)).toBeNull();
  });

  it("answers none when neither the server nor the panel holds a provider", async () => {
    const store = await freshStore();
    const resolution = await resolveChat({ environment: {}, store });

    expect(resolution.source).toBe("none");
    expect(resolution.provider).toBeNull();
    expect(resolution.key).toBe("");
    expect(chatProblem(resolution)?.toLowerCase()).toContain("connect your ai in the panel");
  });

  it("keeps the server winning when it names a key it does not carry", async () => {
    const store = await freshStore();

    await withPanelChat(store, {});

    const resolution = await resolveChat({
      environment: { ENCRYPTION_KEY: key, CHAT_PROVIDER: "openai", OPENAI_API_KEY: "  " },
      store,
    });

    expect(resolution.source).toBe("server");
    expect(resolution.provider).toBe("openai");
    expect(resolution.missing).toEqual(["OPENAI_API_KEY"]);
    expect(chatProblem(resolution)).toContain("OPENAI_API_KEY");
    expect(chatProblem(resolution)).not.toContain(panelKey);
  });

  // Decision 23 of the third amendment: the resolver checks a panel row against the catalogue before it trusts it. A row
  // that names a provider Cited does not know is not a provider: it resolves with a problem, so no model is built from
  // it and the step that reads this resolution asks for attention (the Major M-8 of
  // `katalis-dev/tasks/revision-community-13c.md`).
  it("does not trust a panel row that names a provider outside the catalogue", async () => {
    const store = await freshStore();

    await withPanelChat(store, { provider: "unknown-provider" });

    const resolution = await resolveChat({ environment: { ENCRYPTION_KEY: key }, store });

    expect(resolution.source).toBe("panel");
    expect(resolution.provider).toBeNull();
    expect(chatProblem(resolution)).toContain("not one Cited knows");
    expect(chatProblem(resolution)).not.toContain(panelKey);
    expect(chatConfigured(resolution)).toBe(false);
  });

  // The same check guards the provider the server environment names: an unknown value is a problem of the
  // installation that the panel shows, not an exception that leaves the page without an answer.
  it("resolves a server provider Cited does not know with a problem instead of an exception", async () => {
    const store = await freshStore();

    const resolution = await resolveChat({ environment: { CHAT_PROVIDER: "chatgpt" }, store });

    expect(resolution.source).toBe("server");
    expect(resolution.provider).toBeNull();
    expect(chatProblem(resolution)).toContain("not one Cited knows");
    expect(chatConfigured(resolution)).toBe(false);
  });

  it("keeps the ciphertext in the row and never the key", async () => {
    const store = await freshStore();

    await withPanelChat(store, {});

    const row = await store.readProviderSetting("chat");

    expect(row?.keyCiphertext?.startsWith("v1:")).toBe(true);
    expect(JSON.stringify(row)).not.toContain(panelKey);
    expect(row?.keyLast4).toBe("9876");
  });

  it("has no panel provider when the panel holds nothing", async () => {
    const store = await freshStore();

    await store.deleteProviderSetting("chat");

    expect(await store.readProviderSetting("chat")).toBeNull();
  });

  it("says a saved key cannot be read when the encryption key of the server changed", async () => {
    const store = await freshStore();
    const sealed = sealSecret(panelKey, { ENCRYPTION_KEY: otherKey });

    if (sealed.ok === false) {
      throw new Error("the seal failed");
    }

    await store.saveProviderSetting({
      kind: "chat",
      provider: "deepseek",
      model: "deepseek-flash",
      keyCiphertext: sealed.value,
      keyLast4: "9876",
      baseUrl: null,
      mode: null,
      testedAt: "2026-09-29T10:00:00.000Z",
      testLatencyMs: 120,
    });

    const resolution = await resolveChat({ environment: { ENCRYPTION_KEY: key }, store });

    expect(resolution.source).toBe("panel");
    expect(resolution.keyState).toBe("unreadable");
    expect(resolution.key).toBe("");
    expect(chatProblem(resolution)).toContain("cannot be read");
    expect(chatProblem(resolution)).not.toContain(panelKey);
  });
});

describe("resolveEmbeddings", () => {
  it("uses the server value first", async () => {
    const store = await freshStore();

    await store.saveProviderSetting({
      kind: "embeddings",
      provider: "openai",
      model: "text-embedding-3-small",
      keyCiphertext: null,
      keyLast4: null,
      baseUrl: null,
      mode: "keyword",
      testedAt: null,
      testLatencyMs: null,
    });

    const resolution = await resolveEmbeddings({
      environment: { EMBEDDINGS_PROVIDER: "fake" },
      store,
    });

    expect(resolution.source).toBe("server");
    expect(resolution.mode).toBe("vectors");
    expect(resolution.provider).toBe("fake");
  });

  it("takes the keyword mode of the panel", async () => {
    const store = await freshStore();

    await store.saveProviderSetting({
      kind: "embeddings",
      provider: "keyword",
      model: null,
      keyCiphertext: null,
      keyLast4: null,
      baseUrl: null,
      mode: "keyword",
      testedAt: "2026-09-29T10:00:00.000Z",
      testLatencyMs: null,
    });

    const resolution = await resolveEmbeddings({ environment: {}, store });

    expect(resolution.source).toBe("panel");
    expect(resolution.mode).toBe("keyword");
    expect(resolution.provider).toBeNull();
    expect(embeddingsProblem(resolution)).toBeNull();
    expect(embeddingsSignature(resolution)).toBe("keyword");
  });

  it("takes an embeddings provider of the panel with its own key", async () => {
    const store = await freshStore();
    const sealed = sealSecret("sk-embeddings-0000000000004321", { ENCRYPTION_KEY: key });

    if (sealed.ok === false) {
      throw new Error("the seal failed");
    }

    await store.saveProviderSetting({
      kind: "embeddings",
      provider: "openai",
      model: "text-embedding-3-small",
      keyCiphertext: sealed.value,
      keyLast4: "4321",
      baseUrl: "http://127.0.0.1:9/v1",
      mode: null,
      testedAt: "2026-09-29T10:00:00.000Z",
      testLatencyMs: 80,
    });

    const resolution = await resolveEmbeddings({ environment: { ENCRYPTION_KEY: key }, store });

    expect(resolution.source).toBe("panel");
    expect(resolution.mode).toBe("vectors");
    expect(resolution.provider).toBe("openai");
    expect(resolution.model).toBe("text-embedding-3-small");
    expect(resolution.key).toBe("sk-embeddings-0000000000004321");
    expect(resolution.dimensions).toBe(1536);
    expect(embeddingsSignature(resolution)).toContain("openai");
    expect(embeddingsSignature(resolution)).not.toContain("4321");
  });

  it("answers none when neither the server nor the panel holds embeddings", async () => {
    const store = await freshStore();
    const resolution = await resolveEmbeddings({ environment: {}, store });

    expect(resolution.source).toBe("none");
    expect(resolution.mode).toBe("none");
    expect(embeddingsProblem(resolution)).toContain("EMBEDDINGS_PROVIDER");
  });

  it("still refuses an unknown embeddings provider of the server", async () => {
    const store = await freshStore();

    await expect(
      resolveEmbeddings({ environment: { EMBEDDINGS_PROVIDER: "lo-que-sea" }, store }),
    ).rejects.toThrowError(/EMBEDDINGS_PROVIDER must be one of/);
  });
});

describe("the tables this change added", () => {
  it("says which ones the store has to carry, for the reader of the state", () => {
    // Task 10.6 of the contract: `scripts/store-state.ts` prints the tables of the schema, and this list is the one
    // it reads. The names of the end are the ones this change and the guided setup added to the schema.
    expect(storeTables).toContain("documents");
    expect(storeTables).toContain("passages");
    expect(storeTables).toContain("passages_fts");
    expect(storeTables).toContain("rate_limits");
    expect(storeTables).toContain("model_calls");
    expect(storeTables).toContain("conversations");
    expect(storeTables).toContain("login_attempts");
    expect(storeTables).toContain("business");
    expect(storeTables.slice(-4)).toEqual([
      "provider_settings",
      "provider_tests",
      "document_index",
      "setup_flags",
    ]);
    expect(new Set(storeTables).size).toBe(storeTables.length);
  });
});
