// @vitest-environment node
import { randomBytes } from "node:crypto";
import { describe, expect, it } from "vitest";
import { encryptionAvailable, lastFour, openSecret, sealSecret } from "@/lib/secrets";

// Requirement "The owner connects a provider in the panel" of `specs/provider-settings/spec.md` and decision 1 of
// `design.md`: a key is stored encrypted with AES-256-GCM under `ENCRYPTION_KEY` and never falls back to plaintext.
// The keys of this file are generated by the run: nothing that looks like a real key is committed.

const key = randomBytes(32).toString("base64");
const otherKey = randomBytes(32).toString("base64");
const withKey = (value: string): Record<string, string | undefined> => ({ ENCRYPTION_KEY: value });
const secret = "sk-de-prueba-0000000000001234";

describe("lib/secrets seals a key with AES-256-GCM", () => {
  it("round trips the key and never carries it in clear", () => {
    const sealed = sealSecret(secret, withKey(key));

    expect(sealed.ok).toBe(true);

    if (sealed.ok === false) {
      return;
    }

    expect(sealed.value.startsWith("v1:")).toBe(true);
    expect(sealed.value).not.toContain(secret);
    expect(sealed.value.split(":")).toHaveLength(4);

    const opened = openSecret(sealed.value, withKey(key));

    expect(opened).toEqual({ ok: true, value: secret });
  });

  it("uses a fresh nonce for every seal", () => {
    const first = sealSecret(secret, withKey(key));
    const second = sealSecret(secret, withKey(key));

    expect(first.ok && second.ok).toBe(true);

    if (first.ok === false || second.ok === false) {
      return;
    }

    expect(first.value).not.toBe(second.value);
    expect(first.value.split(":")[1]).not.toBe(second.value.split(":")[1]);
    expect(openSecret(first.value, withKey(key))).toEqual({ ok: true, value: secret });
    expect(openSecret(second.value, withKey(key))).toEqual({ ok: true, value: secret });
  });

  it("detects a tampered value instead of returning a wrong key", () => {
    const sealed = sealSecret(secret, withKey(key));

    if (sealed.ok === false) {
      throw new Error("the seal failed");
    }

    const [version, nonce, ciphertext, tag] = sealed.value.split(":");
    const flip = (value: string): string =>
      `${value.startsWith("A") ? "B" : "A"}${value.slice(1)}`;

    expect(openSecret(`${version}:${nonce}:${flip(ciphertext ?? "")}:${tag}`, withKey(key))).toEqual({
      ok: false,
      reason: "corrupt",
    });
    expect(openSecret(`${version}:${nonce}:${ciphertext}:${flip(tag ?? "")}`, withKey(key))).toEqual({
      ok: false,
      reason: "corrupt",
    });
    expect(openSecret(`${version}:${nonce}:${ciphertext}`, withKey(key))).toEqual({
      ok: false,
      reason: "corrupt",
    });
    expect(openSecret("en-claro", withKey(key))).toEqual({ ok: false, reason: "corrupt" });
    expect(openSecret("", withKey(key))).toEqual({ ok: false, reason: "corrupt" });
  });

  it("refuses to seal without an encryption key and saves nothing in clear", () => {
    expect(sealSecret(secret, withKey(""))).toEqual({ ok: false, reason: "no_key" });
    expect(sealSecret(secret, {})).toEqual({ ok: false, reason: "no_key" });
    expect(openSecret(`v1:a:b:c`, withKey(""))).toEqual({ ok: false, reason: "no_key" });
    expect(encryptionAvailable(withKey(""))).toBe(false);
    expect(encryptionAvailable(withKey(key))).toBe(true);
  });

  it("refuses an encryption key that is not 32 bytes of base64", () => {
    expect(sealSecret(secret, withKey("no-es-base64!!"))).toEqual({ ok: false, reason: "bad_key" });
    expect(sealSecret(secret, withKey(randomBytes(16).toString("base64")))).toEqual({
      ok: false,
      reason: "bad_key",
    });
    expect(encryptionAvailable(withKey("corta"))).toBe(false);
  });

  it("refuses a value sealed with another key", () => {
    const sealed = sealSecret(secret, withKey(key));

    if (sealed.ok === false) {
      throw new Error("the seal failed");
    }

    expect(openSecret(sealed.value, withKey(otherKey))).toEqual({ ok: false, reason: "corrupt" });
  });

  it("keeps the last four characters for the panel", () => {
    expect(lastFour("sk-de-prueba-0000000000001234")).toBe("1234");
    expect(lastFour("ab")).toBe("ab");
    expect(lastFour("")).toBe("");
    expect(lastFour("  espacio  ")).toBe("acio");
  });
});
